"""Tab 4: PQC Shock Simulator — Phase 2/3 Monte Carlo results dashboard.

Reads ``results/pqc_sweep.csv`` (generated by scripts/run_phase2_sweep.py)
and renders interactive Plotly charts plus KPI summary cards.

FIX #5: KPI cards now read dynamically from the loaded DataFrame instead
of being hard-coded to stale values.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

DATA_PATH = Path("results/pqc_sweep.csv")


@st.cache_data(ttl=300)
def load_sweep_data(path: Path = DATA_PATH) -> pd.DataFrame:
    """Load and validate Monte Carlo sweep results."""
    if not path.exists():
        st.error(f"Sweep data not found at {path}. Run scripts/run_phase2_sweep.py first.")
        return pd.DataFrame()

    df = pd.read_csv(path)

    required_cols = [
        "chain", "pqc_fraction", "seed", "num_blocks",
        "avg_block_size_bytes", "avg_txs_per_block",
        "avg_propagation_p50_ms", "avg_propagation_p90_ms",
        "std_propagation_p90_ms", "mempool_evictions",
    ]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        st.error(f"Missing columns in sweep CSV: {missing}")
        return pd.DataFrame()

    return df


# ---------------------------------------------------------------------------
# KPI helpers — FIX #5: read from DataFrame, not hard-coded constants
# ---------------------------------------------------------------------------

def compute_kpis(df: pd.DataFrame) -> dict:
    """Compute KPI values dynamically from the sweep DataFrame.

    FIX #5: Previously these were hard-coded constants (e.g. p90_baseline=45.2).
    Now they are derived from the actual simulation data so the dashboard
    always reflects the current run.
    """
    if df.empty:
        return {}

    # Baseline: Ed25519 / 0% PQC runs
    baseline_mask = df["pqc_fraction"] == 0.0
    pqc_full_mask = df["pqc_fraction"] == 1.0

    kpis = {}

    if baseline_mask.any():
        kpis["p90_baseline_ms"] = float(df.loc[baseline_mask, "avg_propagation_p90_ms"].mean())
        kpis["p50_baseline_ms"] = float(df.loc[baseline_mask, "avg_propagation_p50_ms"].mean())
        kpis["avg_block_size_baseline_bytes"] = float(
            df.loc[baseline_mask, "avg_block_size_bytes"].mean()
        )
        kpis["avg_txs_baseline"] = float(df.loc[baseline_mask, "avg_txs_per_block"].mean())

    if pqc_full_mask.any():
        kpis["p90_pqc_ms"] = float(df.loc[pqc_full_mask, "avg_propagation_p90_ms"].mean())
        kpis["p50_pqc_ms"] = float(df.loc[pqc_full_mask, "avg_propagation_p50_ms"].mean())
        kpis["avg_block_size_pqc_bytes"] = float(
            df.loc[pqc_full_mask, "avg_block_size_bytes"].mean()
        )
        kpis["avg_txs_pqc"] = float(df.loc[pqc_full_mask, "avg_txs_per_block"].mean())
        kpis["avg_evictions_pqc"] = float(df.loc[pqc_full_mask, "mempool_evictions"].mean())

    if "p90_baseline_ms" in kpis and "p90_pqc_ms" in kpis:
        kpis["p90_degradation_pct"] = (
            (kpis["p90_pqc_ms"] - kpis["p90_baseline_ms"]) / kpis["p90_baseline_ms"] * 100
        )

    return kpis


# ---------------------------------------------------------------------------
# Main render function
# ---------------------------------------------------------------------------

def render() -> None:
    """Render the PQC Shock Simulator tab."""
    st.header("PQC Shock Simulator — Monte Carlo Results")

    df = load_sweep_data()
    if df.empty:
        st.info("No sweep data available. Run scripts/run_phase2_sweep.py to generate results.")
        return

    # -----------------------------------------------------------------------
    # Sidebar filters
    # -----------------------------------------------------------------------
    with st.sidebar:
        st.subheader("Filters")
        chains = sorted(df["chain"].unique().tolist())
        selected_chains = st.multiselect(
            "Chains", chains, default=chains, key="pqc_chains"
        )
        pqc_fractions = sorted(df["pqc_fraction"].unique().tolist())
        selected_fracs = st.multiselect(
            "PQC Fraction", pqc_fractions, default=pqc_fractions, key="pqc_fracs"
        )

    filtered_df = df[
        df["chain"].isin(selected_chains)
        & df["pqc_fraction"].isin(selected_fracs)
    ].copy()

    if filtered_df.empty:
        st.warning("No data matches current filters.")
        return

    # -----------------------------------------------------------------------
    # KPI Cards — FIX #5: dynamic values from DataFrame
    # -----------------------------------------------------------------------
    st.subheader("Key Performance Indicators")
    kpis = compute_kpis(filtered_df)

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        if "p90_baseline_ms" in kpis:
            st.metric(
                label="P90 Latency (Baseline)",
                value=f"{kpis['p90_baseline_ms']:.1f} ms",
                help="Median P90 propagation latency at 0% PQC adoption",
            )
    with col2:
        if "p90_pqc_ms" in kpis:
            delta_str = None
            if "p90_degradation_pct" in kpis:
                delta_str = f"{kpis['p90_degradation_pct']:+.1f}%"
            st.metric(
                label="P90 Latency (100% PQC)",
                value=f"{kpis['p90_pqc_ms']:.1f} ms",
                delta=delta_str,
                delta_color="inverse",
                help="Median P90 propagation latency at 100% PQC adoption",
            )
    with col3:
        if "avg_txs_baseline" in kpis and "avg_txs_pqc" in kpis:
            tx_delta = kpis["avg_txs_pqc"] - kpis["avg_txs_baseline"]
            st.metric(
                label="Avg Txs/Block (PQC vs Base)",
                value=f"{kpis['avg_txs_pqc']:.0f}",
                delta=f"{tx_delta:+.0f}",
                delta_color="inverse",
                help="Average transactions per block at 100% PQC vs baseline",
            )
    with col4:
        if "avg_evictions_pqc" in kpis:
            st.metric(
                label="Avg Mempool Evictions (PQC)",
                value=f"{kpis['avg_evictions_pqc']:.0f}",
                help="Average mempool evictions per run at 100% PQC adoption",
            )

    # -----------------------------------------------------------------------
    # Chart 1: P90 propagation vs PQC fraction (box plot)
    # -----------------------------------------------------------------------
    st.subheader("Propagation Latency vs PQC Adoption")

    agg_df = (
        filtered_df.groupby(["chain", "pqc_fraction"])
        .agg(
            mean_p90=("avg_propagation_p90_ms", "mean"),
            std_p90=("avg_propagation_p90_ms", "std"),
            mean_p50=("avg_propagation_p50_ms", "mean"),
            count=("seed", "count"),
        )
        .reset_index()
    )

    fig1 = px.line(
        agg_df,
        x="pqc_fraction",
        y="mean_p90",
        color="chain",
        error_y="std_p90",
        markers=True,
        labels={
            "pqc_fraction": "PQC Adoption Fraction",
            "mean_p90": "Mean P90 Propagation (ms)",
            "chain": "Chain",
        },
        title="P90 Block Propagation Latency vs PQC Adoption Fraction",
    )
    fig1.update_layout(xaxis_tickformat=".0%")
    st.plotly_chart(fig1, use_container_width=True)

    # -----------------------------------------------------------------------
    # Chart 2: Throughput (txs/block) vs PQC fraction
    # -----------------------------------------------------------------------
    st.subheader("Transaction Throughput vs PQC Adoption")

    agg_tx = (
        filtered_df.groupby(["chain", "pqc_fraction"])
        .agg(mean_txs=("avg_txs_per_block", "mean"))
        .reset_index()
    )

    fig2 = px.bar(
        agg_tx,
        x="pqc_fraction",
        y="mean_txs",
        color="chain",
        barmode="group",
        labels={
            "pqc_fraction": "PQC Adoption Fraction",
            "mean_txs": "Avg Transactions per Block",
            "chain": "Chain",
        },
        title="Average Transactions per Block vs PQC Adoption",
    )
    fig2.update_layout(xaxis_tickformat=".0%")
    st.plotly_chart(fig2, use_container_width=True)

    # -----------------------------------------------------------------------
    # Chart 3: Mempool evictions
    # -----------------------------------------------------------------------
    if filtered_df["mempool_evictions"].sum() > 0:
        st.subheader("Mempool Evictions")

        evict_agg = (
            filtered_df.groupby(["chain", "pqc_fraction"])
            .agg(mean_evictions=("mempool_evictions", "mean"))
            .reset_index()
        )

        fig3 = px.area(
            evict_agg,
            x="pqc_fraction",
            y="mean_evictions",
            color="chain",
            labels={
                "pqc_fraction": "PQC Adoption Fraction",
                "mean_evictions": "Avg Mempool Evictions per Run",
                "chain": "Chain",
            },
            title="Mempool Evictions vs PQC Adoption",
        )
        fig3.update_layout(xaxis_tickformat=".0%")
        st.plotly_chart(fig3, use_container_width=True)

    # -----------------------------------------------------------------------
    # Raw data table
    # -----------------------------------------------------------------------
    with st.expander("Raw Monte Carlo Data"):
        st.dataframe(
            filtered_df.sort_values(["chain", "pqc_fraction", "seed"]),
            use_container_width=True,
        )
        csv_bytes = filtered_df.to_csv(index=False).encode()
        st.download_button(
            label="Download CSV",
            data=csv_bytes,
            file_name="pqc_sweep_filtered.csv",
            mime="text/csv",
        )
